# Generated by Django 3.1.5 on 2021-04-04 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('ADid', models.AutoField(primary_key=True, serialize=False)),
                ('ADusername', models.CharField(max_length=100, verbose_name='Admin username')),
                ('ADpassword', models.CharField(max_length=50, verbose_name='Admin password')),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='User First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='User Last Name')),
                ('username', models.CharField(max_length=100, verbose_name='UserName')),
                ('UserImg', models.ImageField(upload_to='UserImage/')),
                ('recorded_at', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Created At')),
                ('user_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('user_database', models.CharField(choices=[('M', 'My Database'), ('O', 'ORL Database')], max_length=1)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
