# Generated by Django 3.1.5 on 2021-04-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_database',
            field=models.CharField(choices=[('My Database', 'My Database'), ('ORL Database', 'ORL Database')], default='My Database', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
    ]
