# Generated by Django 3.1.5 on 2021-04-06 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0006_auto_20210406_2009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
