# Generated by Django 3.1.5 on 2021-04-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0007_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
