# Generated by Django 3.1.5 on 2021-04-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0008_client_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_created_ds',
            field=models.BooleanField(default=False),
        ),
    ]
