# Generated by Django 3.1.5 on 2021-05-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0010_dataset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='ds1',
            new_name='dataset',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='ds2',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='ds3',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='ds4',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='ds5',
        ),
    ]
