# Generated by Django 3.1.5 on 2021-05-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0011_auto_20210502_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='user_database',
            field=models.CharField(choices=[('MyDatabase', 'MyDatabase'), ('ORLDatabase', 'ORLDatabase')], default='My Database', max_length=20),
        ),
    ]
