# Generated by Django 3.1.5 on 2021-05-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0012_auto_20210502_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(max_length=100, verbose_name='Client  Name')),
                ('TrainImg', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Training',
                'verbose_name_plural': 'Trainings',
            },
        ),
    ]
