# Generated by Django 3.1.5 on 2021-05-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0013_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_trained',
            field=models.BooleanField(default=False),
        ),
    ]
