# Generated by Django 3.1.5 on 2021-05-21 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0014_client_is_trained'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='UserImg',
        ),
    ]
