# Generated by Django 3.1.5 on 2021-04-06 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='admin',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='adminImg',
            new_name='userImg',
        ),
    ]
