# Generated by Django 3.1.5 on 2021-05-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210406_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width_pca', models.IntegerField()),
                ('height_pca', models.IntegerField()),
                ('scaleFactor', models.IntegerField()),
                ('minNeighbors', models.IntegerField()),
                ('width_frame', models.IntegerField()),
                ('height_frame', models.IntegerField()),
                ('rec_color', models.CharField(max_length=10)),
                ('rec_stroke', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'Parameters',
            },
        ),
    ]
