# Generated by Django 3.1.5 on 2021-05-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='height_frame',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='height_pca',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='minNeighbors',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='rec_color',
            field=models.CharField(default='red', max_length=10),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='rec_stroke',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='scaleFactor',
            field=models.IntegerField(default=1.1),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='width_frame',
            field=models.IntegerField(default=800),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='width_pca',
            field=models.IntegerField(default=200),
        ),
    ]
