# Generated by Django 3.1.5 on 2021-05-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210525_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='para_name',
            field=models.CharField(default='Parameter', max_length=10),
        ),
    ]
