# Generated by Django 3.1.5 on 2021-06-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_parameter_para_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='BlockSize',
            field=models.IntegerField(default=8),
        ),
    ]
